In [7]:
import numpy as np

In [61]:
arr=np.random.randint(1,101,(5,4))
arr

array([[70, 87,  7, 26],
       [98, 12, 32, 17],
       [41, 86, 76, 15],
       [61, 13, 99, 31],
       [19, 44, 46, 30]])

In [9]:
np.sort(arr)

array([[ 5,  8, 58, 77],
       [41, 57, 68, 82],
       [18, 18, 21, 43],
       [ 3, 24, 82, 94],
       [16, 57, 60, 98]])

In [62]:
np.argsort(arr[:1])

array([[2, 3, 0, 1]], dtype=int64)

In [6]:
np.sort(arr,axis=1)

array([[ 1, 35, 38, 54],
       [19, 23, 73, 85],
       [28, 32, 50, 73],
       [26, 56, 70, 91],
       [ 1, 31, 44, 82]])

In [15]:
np.sort((arr.reshape(-1))).reshape(5,4)

array([[ 3,  5,  8, 16],
       [18, 18, 21, 24],
       [41, 43, 57, 57],
       [58, 60, 68, 77],
       [82, 82, 94, 98]])

In [17]:
marks = np.array([[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]])
marks

array([[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]])

In [25]:
extra_subject =np.array([41, 87, 72, 36, 92]).reshape(-1,1)
marks=np.append(marks,extra_subject,axis=1)

In [26]:
rec1 = np.array([77, 83, 98, 95, 89]).reshape(1,-1)
rec2 = np.array([92, 71, 52, 61, 53]).reshape(1,-1)
np.append(marks,(np.concatenate([rec1,rec2])),axis=0)

array([[13, 10,  9, 33, 41],
       [63, 46, 90, 42, 87],
       [39, 76, 13, 29, 72],
       [82,  9, 29, 78, 36],
       [67, 61, 59, 36, 92],
       [77, 83, 98, 95, 89],
       [92, 71, 52, 61, 53]])

In [27]:
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])

In [29]:
np.unique(arr,axis=0)

array([[0, 9, 1, 2, 8, 8],
       [1, 2, 3, 3, 1, 1],
       [1, 2, 3, 8, 8, 8]])

In [30]:
np.unique(arr,axis=1)

array([[1, 1, 2, 3, 3],
       [0, 8, 9, 1, 2],
       [1, 8, 2, 3, 8],
       [1, 1, 2, 3, 3]])

In [31]:
np.flip(arr)

array([[1, 1, 3, 3, 2, 1],
       [8, 8, 8, 3, 2, 1],
       [8, 8, 2, 1, 9, 0],
       [1, 1, 3, 3, 2, 1]])

In [32]:
arr =np.array ([[1,2,3,4,5], 
      [10,-3,30,4,5], 
      [3,2,5,-4,5], 
      [9,7,3,6,5]] 
)
X = 6

In [38]:
arr[np.where(arr>X)]


array([10, 30,  9,  7])

In [45]:
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)
flat=np.concatenate([arr1,arr2,arr3])
flat

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
arr


array([[448, 563, 418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458,
        387, 262, 613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967,
        277, 470, 336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592,
        997, 137, 340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932,
        645, 952, 921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251,
        957, 103, 627, 920, 824, 356, 825, 173, 323, 372, 960, 710, 464,
        244, 782, 763, 635, 436, 774, 171, 469, 178, 458, 624, 211, 771,
        270, 308, 231, 952, 514, 699, 702, 433, 900, 373, 318, 998, 265,
        503, 320, 230, 324, 922, 967, 620, 743, 527, 117, 566, 804, 123,
        946, 587, 227, 853, 757, 944, 328, 855, 930, 325, 729, 426, 514,
        296, 879, 575, 936, 705, 209, 191, 743, 510, 513, 628, 559, 658,
        528, 395, 525, 922, 136, 496, 225, 895, 975, 263, 908, 420, 711,
        800, 976, 786, 235, 930, 859, 618, 226, 695, 460, 218, 483, 490,
        803, 621, 453, 193, 607, 677, 637, 728, 724

In [49]:
np.delete(arr,np.argmax(arr))

array([448, 563, 418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458,
       387, 262, 613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967,
       277, 470, 336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592,
       997, 137, 340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932,
       645, 952, 921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251,
       957, 103, 627, 920, 824, 356, 825, 173, 323, 372, 960, 710, 464,
       244, 782, 763, 635, 436, 774, 171, 469, 178, 458, 624, 211, 771,
       270, 308, 231, 952, 514, 699, 702, 433, 900, 373, 318, 265, 503,
       320, 230, 324, 922, 967, 620, 743, 527, 117, 566, 804, 123, 946,
       587, 227, 853, 757, 944, 328, 855, 930, 325, 729, 426, 514, 296,
       879, 575, 936, 705, 209, 191, 743, 510, 513, 628, 559, 658, 528,
       395, 525, 922, 136, 496, 225, 895, 975, 263, 908, 420, 711, 800,
       976, 786, 235, 930, 859, 618, 226, 695, 460, 218, 483, 490, 803,
       621, 453, 193, 607, 677, 637, 728, 724, 534, 748, 291, 19

In [48]:
np.delete(arr,np.argmin(arr))

array([448, 563, 418, 240, 507, 362, 345, 236, 719, 291, 298, 639, 458,
       387, 262, 613, 267, 882, 181, 425, 790, 635, 889, 818, 872, 967,
       277, 470, 336, 920, 917, 295, 557, 830, 506, 385, 353, 975, 592,
       997, 137, 340, 222, 215, 472, 459, 617, 649, 935, 956, 914, 932,
       645, 952, 921, 490, 527, 972, 278, 307, 840, 958, 246, 449, 251,
       957, 627, 920, 824, 356, 825, 173, 323, 372, 960, 710, 464, 244,
       782, 763, 635, 436, 774, 171, 469, 178, 458, 624, 211, 771, 270,
       308, 231, 952, 514, 699, 702, 433, 900, 373, 318, 998, 265, 503,
       320, 230, 324, 922, 967, 620, 743, 527, 117, 566, 804, 123, 946,
       587, 227, 853, 757, 944, 328, 855, 930, 325, 729, 426, 514, 296,
       879, 575, 936, 705, 209, 191, 743, 510, 513, 628, 559, 658, 528,
       395, 525, 922, 136, 496, 225, 895, 975, 263, 908, 420, 711, 800,
       976, 786, 235, 930, 859, 618, 226, 695, 460, 218, 483, 490, 803,
       621, 453, 193, 607, 677, 637, 728, 724, 534, 748, 291, 19

In [51]:
arr=np.random.randint(100,700,100)
arr

array([252, 689, 151, 509, 316, 288, 665, 148, 290, 510, 620, 263, 455,
       471, 334, 471, 598, 400, 301, 529, 362, 508, 272, 663, 569, 299,
       464, 556, 392, 189, 513, 547, 116, 142, 320, 193, 698, 537, 464,
       224, 326, 263, 312, 364, 253, 588, 157, 468, 476, 279, 403, 670,
       379, 643, 371, 508, 312, 250, 176, 504, 301, 407, 655, 640, 286,
       278, 316, 534, 327, 348, 243, 665, 447, 391, 171, 494, 207, 276,
       469, 674, 502, 276, 334, 142, 150, 227, 321, 585, 245, 568, 352,
       625, 382, 279, 557, 327, 690, 522, 372, 107])

In [53]:
np.clip(arr,100,200)

array([200, 200, 151, 200, 200, 200, 200, 148, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200, 200, 189, 200, 200, 116, 142, 200, 193, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200, 157, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 176, 200, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200, 200, 200, 171, 200, 200, 200,
       200, 200, 200, 200, 200, 142, 150, 200, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200, 200, 107])

In [56]:
arr=np.round(np.random.random(20),3)
arr

array([0.402, 0.912, 0.607, 0.837, 0.824, 0.545, 0.338, 0.195, 0.434,
       0.841, 0.407, 0.56 , 0.439, 0.102, 0.218, 0.594, 0.819, 0.825,
       0.02 , 0.531])

In [57]:
np.percentile(arr,0)

0.02

In [58]:
np.percentile(arr,100)

0.912

In [59]:
np.percentile(arr,51)-np.percentile(arr,50)

0.0026599999999999957