In [2]:
import numpy as np

In [ ]:
# Create a null vector of size 10 but the fifth value which is 1.
a1=np.zeros(10)
a1[5]=1
print(a1)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [5]:
# Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.
a=int(input())
b=int(input())

a1=np.arange(a*b).reshape(5,2)
print(a1)


[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [10]:
#Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.
def create2D(a,b):
    a1=np.ones((a,b))
    a1[1:a-1,1:b-1]=0
    return a1
ar=create2D(6,6)
print(ar)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [11]:
# Create a vector of size 10 with values ranging from 0 to 1, both excluded.
a=np.random.random(10)
print(a)

[0.69847146 0.70788493 0.89853083 0.43536564 0.3196726  0.93543143
 0.89583653 0.5457292  0.56113128 0.11703825]


In [12]:
# Can you create a identity mattrix of shape (3,4). If yes write code for it.
# No, cant create but we can do for 3,3
idm=np.identity(3)
print(idm)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#  Create a 5x5 matrix with row values ranging from 0 to 4.
a=np.arange(5)
for i in range(5):
      a1=(np.arange(4))
      a=np.vstack((a,a1))

arr=np.arange(5)*np.ones((5,1),dtype=int)

arr

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [43]:
#Consider a random integer (in range 1 to 100) vector with shape (10,2) representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

a1=np.random.randint(1,101,(10,2))
a2=np.array([2,3]) 
dis=np.round(np.sqrt(np.sum((a1-a2)**2,axis=1))).astype(int)
dis

array([ 93,  51,  96,  98,  99,  48,  69, 121,  95,  41])

In [46]:

a=np.random.randint(1,100,(6,7,8))
print(a)
print(a[1,6,5])

[[[41 50 21  2 47 77 67 74]
  [16 62 39 85 39 77 52 20]
  [93 96 66 44  8 34 34 60]
  [ 7 33  3 25 32 65 98 46]
  [41 69 65 16 80 82 20 56]
  [97 83 83 97 86 90 23 39]
  [34 90 17 31 19 66 37 79]]

 [[37 36 55 96 24 25 67 92]
  [15 57 94 55 29 71 66 50]
  [44 96 34 51 24 36  5 48]
  [35 71 68 77  1 94 12 34]
  [21 19 46 82 21 24 47 18]
  [62  9 58 47 36 60 45 26]
  [38  9 52 83 99 52 15 78]]

 [[31 29 49 94 29 45  8 58]
  [43 55 60 61 20 57 85 46]
  [43 98 71 82 72 64 96 62]
  [48 48 83 85  5 55 13 50]
  [ 9 63 85 84 54  9 23 79]
  [ 4 47 16 78 69 37 30  1]
  [88 10 14 67 75 76  1 63]]

 [[37  6  7 18 99 13 70 28]
  [34 35 26 93 36 84 56 82]
  [96 42 99 42 25 29 75 24]
  [59 76 32 87 50 82 75 43]
  [23 73  4 69 52 48 69 73]
  [ 2 16 41 83 79 37 79 70]
  [60 75 16 15 31  3 74 60]]

 [[37 49 73 70 87 67 91 82]
  [90 42 16 73 60 41 80  3]
  [33 56 63 11 86  4 39 99]
  [57 30 81 92 87  4 21 86]
  [29 99 65 31 38 42 22 32]
  [90 75 23 16  3  3 14 22]
  [81 11 38 67 18  6 68 43]]

 [[26 69 1

In [48]:
# You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.
l1="1 2 3 4 -8 -10"
nums=np.array(l1.split(),dtype=float)[::-1]
print(nums)

[-10.  -8.   4.   3.   2.   1.]


In [51]:
#Softmax function
arr=np.array([86.03331084 ,37.7285648  ,48.64908087, 87.16563062 ,38.40852563 ,37.20006318])
def softmax(arr):
    if arr.ndim !=1 :
        raise ValueError("give me 1D array")
    res=np.exp(arr)/np.sum((np.exp(arr)))
    return res
ans=softmax(arr)
ans

array([2.43733248e-01, 2.56112114e-22, 1.41628283e-17, 7.56266752e-01,
       5.05514197e-22, 1.50974911e-22])

In [61]:
a=np.random.randint(1,10,(5,5))
b=np.random.randint(1,10,(5,5))
def ver(*args):
    a1=args[0]
    for i in range(1,len(args)):
        a1=np.vstack((a1,args[i]))
    return a1
print(ver(a,b))


[[3 9 9 6 1]
 [4 1 5 3 1]
 [7 1 2 4 4]
 [5 5 1 4 8]
 [7 2 1 8 1]
 [5 3 2 1 2]
 [2 4 8 2 7]
 [9 6 4 2 8]
 [2 4 2 8 4]
 [7 9 4 6 3]]


In [65]:
st="2024-11-12"
end="2024-12-10"
st=np.datetime64(st)
end=np.datetime64(end)
arr=np.arange(st,end+np.timedelta64(1,"D"),dtype="datetime64")
arr

array(['2024-11-12', '2024-11-13', '2024-11-14', '2024-11-15',
       '2024-11-16', '2024-11-17', '2024-11-18', '2024-11-19',
       '2024-11-20', '2024-11-21', '2024-11-22', '2024-11-23',
       '2024-11-24', '2024-11-25', '2024-11-26', '2024-11-27',
       '2024-11-28', '2024-11-29', '2024-11-30', '2024-12-01',
       '2024-12-02', '2024-12-03', '2024-12-04', '2024-12-05',
       '2024-12-06', '2024-12-07', '2024-12-08', '2024-12-09',
       '2024-12-10'], dtype='datetime64[D]')

In [ ]:
#Subtract the mean of each row from a matrix.
mat=np.random.randint(1,10,(3,3))
ans=(mat-np.mean(mat,axis=1).reshape(-1,1))


(3,)

In [ ]:
# swap column-1 of array with column-2 in the array.
mat=np.array([[1, 1, 3],
       [4, 5, 9],
       [7, 7, 1]])
print(mat)
temp=mat[:,0].copy()
mat[:,0]=mat[:,1]
mat[:,1]=temp
mat



[[1 1 3]
 [4 5 9]
 [7 7 1]]


array([[1, 1, 3],
       [5, 4, 9],
       [7, 7, 1]])

In [ ]:
#Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
c=np.vstack((a,b))
ans=np.max(c,axis=0)

array([6, 3, 1, 7, 8])

In [96]:
# Replace odd elements in arrays with -1.
a=np.arange(1,10)
a[a%2==1]=-1
a

array([-1,  2, -1,  4, -1,  6, -1,  8, -1])

In [103]:
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
print(arr1)
#Fetch Every alternate column of the array
arr1[:,::2,]


[[3491 8572 2245 3232 2214]
 [8626 6436 1359 6978 3681]
 [9241 8127 5223 8367 1233]
 [9527 8329 5420 1255  131]
 [6423 1971 5368 3194 1139]
 [7455 2546 4128 4209 6973]
 [9210 7649 3234 7443 5902]
 [2027 5092 1135 9553 4907]]


array([[3491, 2245, 2214],
       [8626, 1359, 3681],
       [9241, 5223, 1233],
       [9527, 5420,  131],
       [6423, 5368, 1139],
       [7455, 4128, 6973],
       [9210, 3234, 5902],
       [2027, 1135, 4907]])

In [107]:
# Normalise the given array
norm=(arr1-np.min(arr1))/(np.max(arr1)-np.min(arr1))
print(norm)

[[0.35661218 0.89588198 0.2243685  0.32912333 0.22107833]
 [0.90161325 0.66917852 0.13033326 0.72670346 0.37677775]
 [0.96688601 0.84865209 0.54043727 0.87412439 0.11696031]
 [0.9972405  0.87009128 0.56134579 0.11929527 0.        ]
 [0.66779877 0.19528762 0.55582679 0.32509021 0.10698366]
 [0.77732965 0.25631501 0.42421991 0.43281681 0.72617279]
 [0.96359584 0.79791976 0.3293356  0.77605604 0.61250265]
 [0.20123116 0.52653364 0.10655912 1.         0.50689875]]


In [119]:
#Write a function which will accept 2 arguments.
#First: A 1D numpy array arr

#Second: An integer n {Please make sure n<=len(arr)}

#Output: The output should be the nth largest item out of the array
a=np.random.randint(1,10,(10))
print(a)

def func(arr,n):
    a=np.sort(arr)
    return a[-10]
print(func(a,2))

[2 2 5 5 6 8 5 5 1 6]
1


In [3]:
#Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
#  Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
arr = np.array([1,2,3])
ans=np.concatenate([np.repeat(arr,3),np.tile(arr,3)])
ans

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])